miniproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from accounts import views as accounts_views


urlpatterns = [
    path('admin/', admin.site.urls),

    # path('admin/', admin.site.urls),
    path('not_authorized/', accounts_views.not_authorized, name='not_authorized'),
    path('register', accounts_views.register, name='Register'),
    path('login', accounts_views.login, name='Login'),
    path('logout', accounts_views.logout, name='Logout'),

    # APPLICAIOTN BASED URLS
    path('', include('welcome.urls')),
    path('account', include('accounts.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

welcome/urls.py
# from django.contrib import admin
from django.urls import path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('', views.index, name='home'),
    path('books', views.book, name='books'),
    path('add_book', views.add_book, name='add_book'),
    path('add_book/<action>', views.add_book, name='add_book_action'),
    path('authors', views.author, name='authors'),
    path('author/<name>', views.author, name='author_page'),
    path('blogs', views.blogs, name='blogs'),
    path('blog_add', views.blog_add, name="add_blog"),
    path('weather', views.weather, name='weather'),
    path('bulk-upload', views.bulk_upload, name='bulk_upload'),

    # Testing/RnD and Debugging Urls/Codes
    path('test', views.test, name='Test'),
]

urlpatterns += staticfiles_urlpatterns()

welcome/models.py
from django.db import models
from django.contrib.postgres.fields import ArrayField
from django.contrib.auth.models import User


class BookMaster(models.Model):
    book_type = models.CharField(max_length=50)
    book_name = models.CharField(max_length=150)
    book_author = models.CharField(max_length=100)
    book_genre = models.CharField(max_length=50)
    book_year = models.CharField(max_length=4)
    book_publications = models.CharField(max_length=100)
    book_pages_count = models.IntegerField()
    book_front_cover = models.ImageField()
    is_active = models.BooleanField(default=False)
    created_date = models.DateTimeField()
    created_by = models.CharField(max_length=10)
    last_modified_date = models.DateTimeField()
    last_modified_by = models.CharField(max_length=10)

    class Meta:
        db_table = "book_master"

    def __str__(self):
        return self.book_name


class BlogCategory(models.Model):
    cat_id = models.CharField(max_length=10, unique=True)
    cat_desc = models.CharField(max_length=50, unique=True)
    is_active = models.BooleanField(default=False)
    created_date = models.DateTimeField()
    created_by = models.CharField(max_length=10)
    last_modified_date = models.DateTimeField()
    last_modified_by = models.CharField(max_length=10)

    class Meta:
        db_table = "blog_category"

    def __str__(self):
        return self.cat_id


class BlogPost(models.Model):
    title = models.CharField(max_length=100)
    category = models.ForeignKey(
        BlogCategory, default=None, on_delete=models.CASCADE)
    tags = models.CharField(max_length=200)
    content = models.TextField()
    created_by = models.ForeignKey(
        User, default=None, on_delete=models.CASCADE)
    privacy_level = models.IntegerField(default=0)
    is_active = models.BooleanField(default=False)
    created_date = models.DateTimeField()
    last_modified_date = models.DateTimeField()

    class Meta:
        db_table = "blog_post"

    def __str__(self):
        return self.title

    @property
    def author(self):
        user = self.created_by
        author = {'username': user.username,
                  'first_name': user.first_name,
                  'last_name': user.last_name}
        return author

    @property
    def cat_desc(self):
        return self.category.cat_desc

welcome/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from .models import BookMaster, BlogPost
from managers.bulk_uploader import zip_uploader
from zipfile import ZipFile
import requests
from django.http import JsonResponse
from datetime import datetime
from .form import BookForm, BlogPostForm
from django.contrib.auth.decorators import login_required
import django


def index(request):
    print(django.get_version())
    context = {'home_page': True}
    return render(request, 'index.html', context)


def weather(request):
    # url = 'http://api.openweathermap.org/data/2.5/weather?lat=28.641942&lon=77.035342&appid=613a7f7cb40ea901b1008c5c9330dd4f&units=metric'
    url = 'http://api.openweathermap.org/data/2.5/weather?q=Delhi,Delhi,India&appid=613a7f7cb40ea901b1008c5c9330dd4f&units=metric'

    x = requests.get(url).json()

    test = f'''
    <img src="http://openweathermap.org/img/w/{x['weather'][0]['icon']}.png" alt="image" />{x['main']['temp']}°C
        <ul>
            <li><b>{x['name']}</b></li>
            <li>{x['weather'][0]['description']}</li>
            <li> Feels <b>{x['main']['feels_like']}°C</b></li>
        </ul>
    '''
    return HttpResponse(test)


def book(request, **kwargs):
    context = {'book_page': True}
    books = BookMaster.objects.filter(is_active=True).all()
    context['books'] = books
    return render(request, 'books_home.html', context)


def add_book(request, **kwargs):
    context = {'add_book_page': True}
    action = kwargs.get('action')
    if action:
        if request.method == "POST":
            try:
                BookMaster.objects.filter(id=request.POST.get(
                    'book_id')).update(is_active=True if action == "restore" else False)
            except Exception as ex:
                pass
            return redirect(f'/add_book/{action}')
        filter = {}
        if action == 'delete':
            context['delete'] = True
            context['page_heading'] = 'Delete Book'
            filter['is_active'] = True
        if action == 'restore':
            context['restore'] = True
            context['page_heading'] = 'Restore Book'
            filter['is_active'] = False
        books = BookMaster.objects.filter(**filter).all()
        context['books'] = books
        return render(request, 'book_add.html', context)

    context['add'] = True
    context['page_heading'] = 'Add New Book'
    form = BookForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        instance = form.save(commit=False)

        instance.is_active = True
        instance.created_date = str(datetime.now())[:19]
        instance.created_by = request.user
        instance.last_modified_date = str(datetime.now())[:19]
        instance.last_modified_by = request.user

        instance.save()
        return redirect("/")

    context['form'] = form
    return render(request, 'book_add.html', context)


def author(request, **kwargs):
    context = {'author_page': True}
    author = kwargs.get('name', None)
    if author:
        return render(request, 'author_page.html', context)
    else:
        context['author'] = author
        return render(request, 'author_home.html', context)


def blogs(request):
    context = {'blogs_home': True}
    posts = BlogPost.objects.all()
    context['posts'] = posts
    return render(request, 'blog_home.html', context)


def blog_add(request):
    context = {'blog_page': True}
    form = BlogPostForm(request.POST or None)
    if form.is_valid():
        instance = form.save(commit=False)

        instance.is_active = True
        instance.created_by = request.user
        instance.created_date = str(datetime.now())[:19]
        instance.last_modified_date = str(datetime.now())[:19]

        instance.save()
        return redirect("/")

    context['form'] = form
    return render(request, 'blog_add.html', context)


# Testing/RnD and Debugging Views/Codes

def bulk_upload(request):
    return render(request, 'bulk_upload.html')


def test(request):
    context = {'test_page': True}

    books = list(BookMaster.objects.filter(book_type='Novel').annotate(test='book_genre').values(
        'book_name', 'book_type', 'book_genre', 'book_pages_count'))

    context['books'] = books

    return render(request, 'test.html', context)


def test2(request):
    context = {}
    return render(request, 'test.html', context)

welcome/templates/add_book.html
{% extends 'base.html' %} {% load static %} {% block content %}

<form enctype="multipart/form-data" action="add_book" method="POST">
  {% csrf_token %}
  <div id="registration-form" class="container">
    <h1>Add New Book</h1>
    <label for="id_book_type">Book type:</label>
    <input type="text" name="book_type" maxlength="50" required id="id_book_type" />

    <label for="id_book_name">Book name:</label>
    <input type="text" name="book_name" maxlength="150" required id="id_book_name" />

    <label for="id_book_author">Book author:</label>
    <input type="text" name="book_author" maxlength="100" required id="id_book_author" />

    <label for="id_book_genre">Book genre:</label>
    <input type="text" name="book_genre" maxlength="50" required id="id_book_genre" />

    <label for="id_book_year">Book year:</label>
    <input type="text" name="book_year" maxlength="4" required id="id_book_year" />

    <label for="id_book_publications">Book publications:</label>
    <input type="text" name="book_publications" maxlength="100" required id="id_book_publications" />

    <label for="id_book_pages_count">Book pages count:</label>
    <input type="number" name="book_pages_count" required id="id_book_pages_count" />

    <label for="id_book_front_cover">Book front cover:</label>
    <input type="file" name="book_front_cover" accept="image/*" required id="id_book_front_cover" />

    <input type="submit" name="Add BooK" id="" />
  </div>
</form>

<!-- <script>
  $(document).ready(function () {

  });
</script> -->

{% endblock %}

welcome/templates/author_home.html
{% extends 'base.html' %} {% load static %} {% block content %}
<div class="main-context container">
  <h1>THIS IS AUTHOR PAGE</h1>
  <div class="under-development"></div>
  <img src="https://freesvg.org/img/men-at-work.png" alt="" />
  <h2>(Under Devlopment...)</h2>
</div>

{% endblock %}

welcome/templates/author_page.html
{% extends 'base.html' %} {% load static %} {% block content %}
<div class="main-context container">
  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Repellendus, minus maiores. Vel labore, sunt illo nesciunt dolorem, pariatur voluptate enim eum quaerat quo explicabo deleniti facere doloribus, corporis voluptatem non! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Amet obcaecati asperiores ipsa enim veniam reprehenderit provident, deleniti sit temporibus, incidunt quaerat dignissimos voluptatum, tempora nihil eius neque saepe totam architecto. Lorem ipsum dolor sit amet
  consectetur adipisicing elit. Sint hic sit perspiciatis asperiores repellat adipisci provident, porro amet labore pariatur dicta incidunt animi culpa dolore repudiandae id nemo optio. Vero.
</div>

{% endblock %}

welcome/templates/blog_add.html
{% extends 'base.html' %} {% load static %} {% block content %}
<div class="main-context container">
  <div class="blog-main">
    <form action="/blog_add" method="POST">
      {% csrf_token %} {% for field in form %} {{field.name}}{{field}} <br />{% endfor %}
      <input type="submit" value="Post" />
    </form>
  </div>
</div>

{% endblock %}

welcome/templates/blog_home.html
{% extends 'base.html' %} {% load static %} {% block content %}
<section id="showcase">
  <div class="container">
    <h1>Blogs Home</h1>
    <h2>Create Blog posts and let everyone knowsyour intresting story or Read some ofthe story of other's life .</h2>
  </div>
</section>
<div class="main-context container">
  <section id="main">
    <div class="blog-top-button">
      <a href="/blog_add"><button class="add-new">Add New</button></a>
    </div>
    <div class="blog-section">
      {% for post in posts %}
      <div class="post-container">
        <img class="post-img-top" src="/media/IMG-20200525-WA0000.jpg" alt="Card image cap" />
        <div class="post-body">
          <h5 class="post-title">{{post.title}}</h5>
          <p class="post-content">{{post.content}}</p>
          <!-- <p class="post-content">{{post.content | slice:":151" }}{% if post.content|length > 115 %}...{% endif %}</p> -->
          <a href="#" class="btn">Read More</a>
        </div>
      </div>
      {% endfor %}
    </div>
    <!--                Section Ends: Best Sellers-->
  </section>

  <aside id="sidebar">
    <h1>Trending</h1>
    <p>This is the test part will be used for side display of trending blog posts <br />Enjoy reading</p>
  </aside>
</div>

{% endblock %}

welcome/templates/blog_read.html
{% extends 'base.html' %} {% load static %} {% block content %}
<div class="main-context container">
  Read a blog
</div>

{% endblock %}

welcome/templates/book_add.html
{% extends 'base.html' %} {% load static %} {% block content %}

<div class="main-context container">
  <div class="page-heading">
    <label>{{page_heading}}</label>
    <div class="page-side-menu">
      {% if not add %}
      <a href="/add_book">Add New Book</a>
      {% endif %} {% if not delete %}
      <a href="/add_book/delete">Delete Book</a>
      {% endif %} {% if not restore %}
      <a href="/add_book/restore">Restore Book</a>
      {% endif %}
    </div>
  </div>
  {% if add %}<!-- ADD New Book-->
  <form enctype="multipart/form-data" action="/add_book" method="POST" class="entry-form">
    {% csrf_token %}
    <label for="id_book_type">Book type:</label>
    <input type="text" name="book_type" maxlength="50" required id="id_book_type" />

    <label for="id_book_name">Book name:</label>
    <input type="text" name="book_name" maxlength="150" required id="id_book_name" />

    <label for="id_book_author">Book author:</label>
    <input type="text" name="book_author" maxlength="100" required id="id_book_author" />

    <label for="id_book_genre">Book genre:</label>
    <input type="text" name="book_genre" maxlength="50" required id="id_book_genre" />

    <label for="id_book_year">Book year:</label>
    <input type="text" name="book_year" maxlength="4" required id="id_book_year" />

    <label for="id_book_publications">Book publications:</label>
    <input type="text" name="book_publications" maxlength="100" required id="id_book_publications" />

    <label for="id_book_pages_count">Book pages count:</label>
    <input type="number" name="book_pages_count" required id="id_book_pages_count" />

    <label for="id_book_front_cover">Book front cover:</label>
    <input type="file" name="book_front_cover" accept="image/*" required id="id_book_front_cover" />

    <input type="submit" name="Add BooK" />
  </form>
  {% else %}<!-- DELETE/RESTORE Old Books-->
  {% for book in books %}
  <div class="book-container book-container-action">
    <img src="{{book.book_front_cover.url}}" alt="" title="{{book.book_name}}" />
    <div class="book-tile" title="{{book.book_name}}">
      {{book.book_name}}
    </div>
    <div class="book-author" title="{{book.book_author}}">
      - {{ book.book_author }}
    </div>

    <div class="book-button">
      <form enctype="multipart/form-data" method="POST" action="/add_book/{% if delete %}delete{% elif restore %}restore{% endif %}">
        {% csrf_token %}
        <input type="hidden" name="book_id" value="{{book.id}}" />
        <button class="btn{% if delete %}Delete{% elif restore %}Restore{% endif %}" type="submit">{% if delete %}Delete{% elif restore %}Restore{% endif %}</button>
      </form>
    </div>
  </div>
  {% endfor %} {% endif %}
</div>

{% endblock %}

welcome/templates/books_home.html
{% extends 'base.html' %} {% load static %} {% block content %}
<section id="showcase">
  <div class="container">
    <h1>Books Home</h1>
    <h2>Browse -> Select Book -> Buy It -> Read Anywhere Anytime.</h2>
  </div>
</section>

<div class="main-context container">
  <section id="main">
    <!--                Section Starts: Best Sellers-->
    <div class="book-section">
      <h1>Best Sellers</h1>

      {% for book in books %}

      <div class="book-container">
        <img src="{{book.book_front_cover.url}}" alt="" title="{{book.book_name}}" />
        <div class="book-tile" title="{{book.book_name}}">
          {{book.book_name}}
        </div>
        <div class="book-author" title="{{book.book_author}}">
          - {{ book.book_author }}
        </div>

        <div class="book-button">
          <button class="btnBookInfo">Info</button>
          <button class="btnBookBuy">Buy</button>
        </div>
      </div>

      {% endfor %}
    </div>
    <!--                Section Ends: Best Sellers-->
  </section>

  <aside id="sidebar">
    <h1>Best Offer</h1>
    <p>This is the test para to check for text in offer section of Book Home page <br />Enjoy reading</p>
  </aside>
</div>

{% endblock %}

welcome/templates/bulk_upload.html
{% extends 'base.html' %} {% block content %}

<div class="main-context container">
  <form action="bulk-upload" method="POST">
    {% csrf_token %}
    <input type="file" name="uploaded_file" />
    <input type="submit" value=" Upload File " />
  </form>
</div>

{% endblock %}

welcome/templates/index.html
{% extends 'base.html' %} {% load static %} {% block content %}
<section id="showcase">
  <div class="container">
    <h1>Welcome to Library</h1>
  <h2>
    All your favorite books are few clicks away, enjoy reading in comfort without leaving your home.<br />
    ALWAYS AT YOUR SERVICE
  </h2>
</section>

<div class="main-context container">
  <section id="main">
    <h1>Welcome</h1>
    <p>
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet, consectetur
      adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
    </p>
  </section>

  <aside id="sidebar">
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco</p>
  </aside>
</div>

{% endblock %}

welcome/templates/test.html
{% extends 'base.html' %}
{% load static %}


	{% block content %}
	<div class="container">
		<h1>Test Page</h1>
		<h2>Values Passed: {{value}}</h2>
		<a href="/add">Add</a>
		{% for book in books %}
			<div>
				<lable>{{book.book_type}}</lable>
				<br>
				<lable>{{book.book_name}}</lable>
				<br>
				<lable>{{book.book_author}}</lable>
				<br>
				<img src="{{book.book_front_cover.url}}" alt="Image Not Available"><br>
			</div>
		{% endfor %}
	</div>
	{% endblock %}